name: Check addon

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Pylint
      run: |
        pip install --upgrade pip
        pip install -q -r requirements.txt
    - name: Check with Pylint
      run: |
        make lint
    - name: Install addon checker
      run: |
        pip install -q kodi-addon-checker
    - name: Check with addon-checker
      run: |
        kodi-addon-checker --branch leia
